global:
  evaluation_interval: 30s
  scrape_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: otel
  honor_labels: true
  static_configs:
  - targets:
    - 'otelcol:9464'
- job_name: otel-collector
  static_configs:
  - targets:
    - 'otel-collector:8888'
- job_name: 'rabbitmq-server'
  static_configs:
    - targets:
        - 'cloudpath-messaging:15692'
- job_name: 'consul-services'
  consul_sd_configs:
    - server:   'cloudpath-discovery:8500'
      services: ['authorization', 'billing', 'content-delivery', 'core', 'hosting', 'internal', 'internal-spa-bff', 'mail', 'public-oauth2', 'public-spa-bff', 'telemetry', 'release', 'start', 'blog']
  relabel_configs:
    - source_labels: ['__meta_consul_service']
      regex:         '(.*)'
      target_label:  'job'
      replacement:   '$1'
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         ',(production|dev),'
      target_label:  'group'
      replacement:   '$1'
  metrics_path: "/actuator/prometheus"
