exporters:
  otlp:
    endpoint: "tracing:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "otel-collector:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
service:
  pipelines:
    traces:
      exporters: [otlp, logging, spanmetrics]
    metrics:
      exporters: [prometheus, logging]