receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 10943040
        read_buffer_size: 10943040
        max_concurrent_streams: 200
        write_buffer_size: 10943040
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  debug:
    verbosity: detailed
  logging:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
  otlp:
    endpoint: http://tempo:4317
    tls:
      insecure: true

processors:
  batch:
    send_batch_max_size: 10000
    timeout: 1s
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

connectors:
  spanmetrics:

extensions:
   # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collector’s performance data
  pprof:
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp, spanmetrics]
    logs:
      receivers: [otlp]
      exporters: [logging, loki]